development:
  adapter: redis
  url: redis://127.0.0.1:6379/1
  
test:
  adapter: async

production:
  adapter: async
  # adapter: redis
  # url: redis://localhost:6379/1
  # channel_prefix: coinfalcon_production
